In [1]:
import os
import sqlite3
import pandas as pd

In [2]:
print(os.getcwd())

c:\Users\anaco\OneDrive\Documentos\GitHub\whiteberry\parte1

In [3]:
connection = sqlite3.connect("sql-murder-mystery.db")

cursor = connection.cursor()

In [4]:
##  to find the names of the tables in this database
pd.read_sql("""
    SELECT name 
    FROM sqlite_master
    WHERE type = 'table'
""", connection)

                     name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution

In [5]:
## find the structure of the `crime_scene_report` table
cursor.execute("""
    SELECT sql 
    FROM sqlite_master
    WHERE name = 'crime_scene_report'
""")

print(cursor.fetchone())

('CREATE TABLE crime_scene_report (\n        date integer,\n        type text,\n        description text,\n        city text\n    )',)

In [6]:
## check the solution 

cursor.execute("INSERT INTO solution VALUES (1, 'XXXXXXXXXXXXXXXXX')")
connection.commit()

In [7]:
cursor.execute("SELECT value FROM solution")
pd.DataFrame(cursor.fetchall(), columns=["value"])

                                     value
0  That's not the right person. Try again!